language: node_js

node_js:
  - "6"
  - "7"
  - "8"

install:
  - npm install
  - npm install -g codecov

after_success:
  - codecov --token=bcace657-3937-44ef-8322-bacadc7a397d

notifications:
  email:
    recipients:
      - alk03073135@gmail.com
    on_success: always
    on_failure: always